services:
  postgres:
    image: postgres:18.0-alpine3.22
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - keycloak_network


  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./cert/fullchain.pem:/etc/nginx/cert/fullchain.pem:ro
#      - ./cert/privkey.pem:/etc/nginx/cert/privkey.pem:ro
    depends_on:
      - keycloak
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    container_name: keycloak_web
    command:
      - start
      - --http-enabled=true          # HTTP 활성화 (Nginx에서 TLS 처리)
      - --hostname=ron-site.iptime.org
      - --hostname-strict=false
      - --proxy-headers=xforwarded
    environment:
      KC_PROXY: edge
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - keycloak_network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"   # 클라이언트 접속
    environment:
      # KRaft 설정 (ZK 없이 동작)
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9094"

      # ★ 필수: KRaft 클러스터 ID
      # 아무 값이나 고정값으로 사용 가능 (예: UUID)
      KAFKA_CLUSTER_ID: "Qv6kRk2sR9Oe2wV3o7bW0Q"  # 원하는 값으로 변경 가능
      CLUSTER_ID: "Qv6kRk2sR9Oe2wV3o7bW0Q"

      # 기본 토픽/로그 설정
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: "3"
      KAFKA_DEFAULT_REPLICATION_FACTOR: "1"

      # 로그 보존 (예: 7일)
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_CLEANUP_POLICY: "delete"

      # 브로커 ID(내부 호환)
      KAFKA_BROKER_ID: "1"

      # 메모리
      KAFKA_HEAP_OPTS: "-Xms512m -Xmx512m"

    volumes:
      - ./data/kafka:/var/lib/kafka/data
    networks:
      - keycloak_network

volumes:
  postgres_data:

networks:
  keycloak_network:
    driver: bridge
